"""把一个`ProjectTemplate`真正写到磁盘上，生成一个可运行的新项目目录。"""

from __future__ import annotations

from pathlib import Path

from ainative_cli.templates import ProjectTemplate


class ProjectAlreadyExistsError(Exception):
    """目标目录已存在且非空时抛出——防止意外覆盖用户已有的工作。"""


def render_pyproject_toml(project_name: str, template: ProjectTemplate) -> str:
    deps = "\n".join(f'    "{pkg}",' for pkg in template.packages)
    return (
        f'[project]\n'
        f'name = "{project_name}"\n'
        f'version = "0.1.0"\n'
        f'description = "Generated by `ainative new --type {template.name}`"\n'
        f'requires-python = ">=3.11"\n'
        f"dependencies = [\n{deps}\n]\n"
    )


def render_readme(project_name: str, template: ProjectTemplate) -> str:
    packages_list = "\n".join(f"- `{pkg}`" for pkg in template.packages)
    return (
        f"# {project_name}\n\n"
        f"Generated by `ainative new {project_name} --type {template.name}`.\n\n"
        f"**{template.description}**\n\n"
        f"## Packages used\n\n{packages_list}\n\n"
        f"## Getting started\n\n"
        f"```bash\n"
        f"uv sync\n"
        f"uv run python main.py\n"
        f"```\n"
    )


def render_env_example() -> str:
    return (
        "# Copy to .env and fill in the values you need.\n"
        "ANTHROPIC_API_KEY=\n"
        "OPENAI_API_KEY=\n"
        "DEEPSEEK_API_KEY=\n"
        "ENVIRONMENT=development\n"
    )


def scaffold_project(target_dir: Path, project_name: str, template: ProjectTemplate, *, force: bool = False) -> list[Path]:
    """在`target_dir`下生成新项目的全部文件，返回写入的文件路径列表。

    Args:
        target_dir: 新项目的目标目录（会被创建，如果不存在）。
        project_name: 项目名称，会写入生成的`pyproject.toml`/`README.md`里。
        template: 要使用的项目模板。
        force: 目标目录已存在且非空时，是否仍然继续写入（覆盖同名文件）。
            默认False——防止意外覆盖用户已有的工作。

    Raises:
        ProjectAlreadyExistsError: `target_dir`已存在且非空，且`force=False`。
    """
    if target_dir.exists() and any(target_dir.iterdir()) and not force:
        raise ProjectAlreadyExistsError(
            f"target directory '{target_dir}' already exists and is not empty; pass force=True to overwrite"
        )

    target_dir.mkdir(parents=True, exist_ok=True)

    files = {
        target_dir / "pyproject.toml": render_pyproject_toml(project_name, template),
        target_dir / "README.md": render_readme(project_name, template),
        target_dir / "main.py": template.main_py,
        target_dir / ".env.example": render_env_example(),
    }

    written: list[Path] = []
    for path, content in files.items():
        path.write_text(content, encoding="utf-8")
        written.append(path)
    return written
